--2022-05-01 12:31:29--  https://raw.githubusercontent.com/harlanc/xiu/master/application/xiu/src/config/config_rtmp_httpflv_hls.toml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 636 [text/plain]
Saving to: ‘config_rtmp_httpflv_hls.toml’

0K                                                       100% 35, 8M = 0s

2022-05-01 12:31:29 (35, 8 MB/s) - ‘config_rtmp_httpflv_hls.toml’ saved [636/636]

